M48
; DRILL file {KiCad 7.0.2} date Tue Jun 20 04:38:43 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-20T04:38:43+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1063
%
G90
G05
T1
X5.6562Y-3.9349
X5.8838Y-3.9349
T2
X4.38Y-3.8009
X4.38Y-3.9191
T3
X4.775Y-4.4136
T4
X7.405Y-4.4136
T5
X3.94Y-3.78
X4.48Y-5.31
X7.5Y-3.8
T0
M30
