#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri May 05 11:44:30 CEST 2023
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto ea260d145f6e46939c5cf3c482ef8197 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot DaS_tb_behav xil_defaultlib.DaS_tb -log elaborate.log"
xelab -wto ea260d145f6e46939c5cf3c482ef8197 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot DaS_tb_behav xil_defaultlib.DaS_tb -log elaborate.log

