#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri May 05 10:32:17 CEST 2023
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim DaS_tb_behav -key {Behavioral:sim_1:Functional:DaS_tb} -tclbatch DaS_tb.tcl -view /home/indi/Documents/EDSP/DaS/DaS_tb_behav.wcfg -log simulate.log"
xsim DaS_tb_behav -key {Behavioral:sim_1:Functional:DaS_tb} -tclbatch DaS_tb.tcl -view /home/indi/Documents/EDSP/DaS/DaS_tb_behav.wcfg -log simulate.log

