webtalk_init -webtalk_dir /home/indi/Documents/EDSP/DaS/DaS.sim/sim_1/behav/xsim/xsim.dir/DaS_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri May  5 11:52:29 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2aad72df-9b3b-4710-9812-2dd3157b18dc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ea260d145f6e46939c5cf3c482ef8197" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "179" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 6900HS Creator Edition" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3293.719 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "4" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "6.82_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "730568_KB" -context "xsim\\usage"
webtalk_transmit -clientid 287405108 -regid "" -xml /home/indi/Documents/EDSP/DaS/DaS.sim/sim_1/behav/xsim/xsim.dir/DaS_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/indi/Documents/EDSP/DaS/DaS.sim/sim_1/behav/xsim/xsim.dir/DaS_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/indi/Documents/EDSP/DaS/DaS.sim/sim_1/behav/xsim/xsim.dir/DaS_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
